### ISSUE TITLE
Cordova v 2.6.0 support?

### ISSUE THREAD

**Issue by bantic** [DrewDahlman/Phonegap-LocalNotification#13]
It appears based on the cordova.js file in the project that this targets cordova v 1.7.0. Will it also work with the latest phonegap/cordova?

**Comment by mymickey** [comment]
I would also like to know

**Comment by DrewDahlman** [comment]
I am currently working on the new version of the plugin so there will be version for phonegap - cordova - cordova 2+ You're move than welcome to fork and help out in the process.

**Comment by Mr-F** [comment]
Can I ask if there is any more information about the update to the project yet?  Just need to do something myself and was wondering how it was developing and what I can do to help with the update.

**Comment by DrewDahlman** [comment]
If you have written an update feel free to fork this and then make a new directory for Cordova 2.0 and add in the plugin!

**Comment by DrewDahlman** [comment]
Merged Code and Added Support for 2.3+
