### ISSUE TITLE
App crashing when canceling a notification

### ISSUE THREAD

**Issue by thmr** [DrewDahlman/Phonegap-LocalNotification#8]
Thanks for the great great plug in! 

I had an small issue when canceling a notification. I was getting the following error and my app was crashing: 

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x1dda1070'

Changing the following line in LocalNotification.m
NSString *notificationId = [arguments objectAtIndex:0];

to 

 NSString *notificationId = [NSString stringWithFormat:@"%@",[arguments objectAtIndex:0]];

Seemed to resolve the issue.  
I hope this helps.

**Comment by DrewDahlman** [comment]
The fix for this was just merged!
